### ISSUE TITLE
Theme Review Checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [Magazine3/accelerated-mobile-pages#2]
**Code**
- [x] No PHP or JS notices.
- [x] Have a valid DOCTYPE declaration and include language_attributes.
- [ ] Validate and/or sanitize untrusted data before entering into the database. All untrusted data should be escaped before output. (See: Data Validation)
- [ ] No removing or modifying non-presentational hooks.
- [ ] Must meet all Theme Check requirements
- [ ] Provide a unique prefix for everything the Theme defines in the public namespace, including options, functions, global variables, constants, post meta, etc. Theme nav menu locations and sidebar IDs are exceptions.
